# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [ published ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/pyproject.toml
      - name: Lint with mypy
        run: |
          uv run mypy --no-strict-optional --ignore-missing-imports --explicit-package-bases aeon
      - name: Check install
        run: |
          uv pip install  -e .
      - name: Build package
        run: uv build
      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_API_TOKEN }}
